version: "3.8"
services:
  postgres:
    container_name: vacancy_management_system_postgres
    image: postgres
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vacancy_management_system